#ifndef TEST_HARNESS_BLOGATOR_HARNESS_CONFIGURATIONPARSERTEST_H
#define TEST_HARNESS_BLOGATOR_HARNESS_CONFIGURATIONPARSERTEST_H

namespace test_harness::blogator {
    struct ConfigurationParserTest { //TODO
        
    };
}

#endif //TEST_HARNESS_BLOGATOR_HARNESS_CONFIGURATIONPARSERTEST_H
