#ifndef BLOGATOR_DOM_HTML5_ATTRIBUTE_H
#define BLOGATOR_DOM_HTML5_ATTRIBUTE_H

namespace blogator::dom::html5 {
    /**
     * HTML5 attributes
     * ref: https://www.w3schools.com/tags/ref_attributes.asp
     */
    enum class Attribute {
        ACCEPT, ACCEPT_CHARSET, ACCESSKEY, ACTION, ALT, ASYNC, AUTOCOMPLETE, AUTOFOCUS, AUTOPLAY,
        CHARSET, CHECKED, CITE, CLASS, COLS, COLSPAN, CONTENT, CONTENTEDITABLE, CONTROLS, COORDS,
        DATA, DATA_X /* data-* */, DATETIME, DEFAULT, DEFER, DIR, DIRNAME, DISABLED, DOWNLOAD, DRAGGABLE,
        ENCTYPE,
        FOR, FORM, FORMACTION,
        HEADERS, HEIGHT, HIDDEN, HIGH, HREF, HREFLANG, HTTP_EQUIV,
        ID, ISMAP,
        KIND,
        LABEL, LANG, LIST, LOOP, LOW,
        MAX, MAXLENGTH, MEDIA, METHOD, MIN, MULTIPLE, MUTED,
        NAME, NOVALIDATE,
        ONABORT, ONAFTERPRINT,
            ONBEFOREPRINT, ONBEFOREUNLOAD, ONBLUR,
            ONCANPLAY, ONCANPLAYTHROUGHT, ONCHANGE, ONCLICK, ONCONTEXTMENU, ONCOPY, ONCUECHANGE, ONCUT,
            ONDBLCLICK, ONDRAG, ONDRAGEND, ONDRAGENTER, ONDRAGLEAVE, ONDRAGOVER, ONDRAGSTART, ONDROP, ONDURATIONCHANGE,
            ONEMPTIED, ONENDED, ONERROR,
            ONFOCUS,
            ONHASHCHANGE,
            ONINPUT, ONINVALID,
            ONKEYDOWN, ONKEYPRESS, ONKEYUP,
            ONLOAD, ONLOADEDDATA, ONLOADEDMETADATA, ONLOADSTART,
            ONMOUSEDOWN, ONMOUSEMOVE, ONMOUSEOUT, ONMOUSEOVER, ONMOUSEUP, ONMOUSEWHEEL,
            ONOFFLINE, ONONLINE,
            ONPAGEHIDE, ONPAGESHOW, ONPASTE, ONPAUSE, ONPLAY, ONPLAYING, ONPOPSTATE, ONPROGRESS,
            ONRATECHANGE, ONRESET, ONRESIZE,
            ONSCROLL, ONSEARCH, ONSEEKED, ONSEEKING, ONSELECT, ONSTALLED, ONSTORAGE, ONSUBMIT, ONSUSPEND,
            ONTIMEUPDATE, ONTOGGLE,
            ONUNLOAD,
            ONVOLUMECHANGE,
            ONWAITING, ONWHEEL,
            OPEN, OPTIMUM,
        PATTERN, PLACEHOLDER, POSTER, PRELOAD,
        READONLY, REL, REQUIRED, REVERSED, ROWS, ROWSPAN,
        SANDBOX, SCOPE, SELECTED, SHAPE, SIZE, SPAN, SPELLCHECK, SRC, SRCDOC, SRCLANG, SRCSET, START, STEP, STYLE,
        TABINDEX, TARGET, TITLE, TRANSLATE, TYPE,
        USEMAP,
        VALUE,
        WIDTH, WRAP
    };
}

#endif //BLOGATOR_DOM_HTML5_ATTRIBUTE_H
