#ifndef BLOGATOR_DOM_HTML5_ATTRIBUTE_H
#define BLOGATOR_DOM_HTML5_ATTRIBUTE_H

namespace blogator::dom::html5 {
    /**
     * HTML5 + ARIA attributes
     */
    enum class Attribute {
        /* HTML5-proper attributes */
        ACCEPT = 0, ACCEPT_CHARSET, ACCESSKEY, ACTION, ALT, ASYNC, AUTOCOMPLETE, AUTOFOCUS, AUTOPLAY,
        CHARSET, CHECKED, CITE, CLASS, COLS, COLSPAN, CONTENT, CONTENTEDITABLE, CONTROLS, COORDS,
        DATA, DATA_X /* data-* */, DATETIME, DEFAULT, DEFER, DIR, DIRNAME, DISABLED, DOWNLOAD, DRAGGABLE,
        ENCTYPE,
        FOR, FORM, FORMACTION,
        HEADERS, HEIGHT, HIDDEN, HIGH, HREF, HREFLANG, HTTP_EQUIV,
        ID, ISMAP,
        KIND,
        LABEL, LANG, LIST, LOOP, LOW,
        MAX, MAXLENGTH, MEDIA, METHOD, MIN, MULTIPLE, MUTED,
        NAME, NOVALIDATE,
        ONABORT, ONAFTERPRINT,
            ONBEFOREPRINT, ONBEFOREUNLOAD, ONBLUR,
            ONCANPLAY, ONCANPLAYTHROUGH, ONCHANGE, ONCLICK, ONCONTEXTMENU, ONCOPY, ONCUECHANGE, ONCUT,
            ONDBLCLICK, ONDRAG, ONDRAGEND, ONDRAGENTER, ONDRAGLEAVE, ONDRAGOVER, ONDRAGSTART, ONDROP, ONDURATIONCHANGE,
            ONEMPTIED, ONENDED, ONERROR,
            ONFOCUS,
            ONHASHCHANGE,
            ONINPUT, ONINVALID,
            ONKEYDOWN, ONKEYPRESS, ONKEYUP,
            ONLOAD, ONLOADEDDATA, ONLOADEDMETADATA, ONLOADSTART,
            ONMOUSEDOWN, ONMOUSEMOVE, ONMOUSEOUT, ONMOUSEOVER, ONMOUSEUP, ONMOUSEWHEEL,
            ONOFFLINE, ONONLINE,
            ONPAGEHIDE, ONPAGESHOW, ONPASTE, ONPAUSE, ONPLAY, ONPLAYING, ONPOPSTATE, ONPROGRESS,
            ONRATECHANGE, ONRESET, ONRESIZE,
            ONSCROLL, ONSEARCH, ONSEEKED, ONSEEKING, ONSELECT, ONSTALLED, ONSTORAGE, ONSUBMIT, ONSUSPEND,
            ONTIMEUPDATE, ONTOGGLE,
            ONUNLOAD,
            ONVOLUMECHANGE,
            ONWAITING, ONWHEEL,
            OPEN, OPTIMUM,
        PATTERN, PLACEHOLDER, POSTER, PRELOAD,
        READONLY, REL, REQUIRED, REVERSED, ROWS, ROWSPAN,
        SANDBOX, SCOPE, SELECTED, SHAPE, SIZE, SIZES, SPAN, SPELLCHECK, SRC, SRCDOC, SRCLANG, SRCSET, START, STEP, STYLE,
        TABINDEX, TARGET, TITLE, TRANSLATE, TYPE,
        USEMAP,
        VALUE,
        WIDTH, WRAP,

        /* Accessible Rich Internet Applications (ARIA) attributes */
        ARIA_X,
        ROLE,

        /* XML namespace */
        XMLNS,

        ENUM_END //Not HTML - used for iterating enums
    };
}

#endif //BLOGATOR_DOM_HTML5_ATTRIBUTE_H
